### ISSUE TITLE
hloc使用问题咨询

### ISSUE THREAD

**Issue by WuZihao12** [Li-Jesse-Jiaze/ov_hloc#3]
感谢你出色的工作！大佬想问下，使用hloc的时候需要预加载环境的3D模型吗？

**Comment by Li-Jesse-Jiaze** [comment]
目前这里只是使用hloc中的方法进行回环检测，还没有加载用hloc构建的3D模型做视觉定位的功能

但你可以尝试在地图保存和读取功能的基础上进行开发，只需要转换以下hloc的3D模型文件，可以按照以下思路

convert map to pose graph

pose graph format:

- pose_graph.txt:

  - index, time_stamp,

  VIO_Tx, VIO_Ty, VIO_Tz, PG_Tx, PG_Ty, PG_Tz, VIO_Qw, VIO_Qx, VIO_Qy, VIO_Qz, PG_Qw, PG_Qx, PG_Qy, PG_Qz, loop_index, loop_info_0, loop_info_1, loop_info_2, loop_info_3, loop_info_4, loop_info_5, loop_info_6, loop_info_7, keypoints_num, height, width

- [i]_keypoints.txt:

  - p_x, p_y, p_x_norm, p_y_norm, score

- [i]_global_desc.dat:

  - 1x4096 cv::Mat written by function in `pose_graph.cpp`

- [i]_local_desc.dat:

  - keypoints_numx256 cv::Mat written by function in `pose_graph.cpp`

*ps: VIO_ and loop_ in pose_graph.txt is not important*

**Comment by WuZihao12** [comment]
想问下你使用NetVLAD替换BoW的代码段在具体哪里呢？

**Comment by Li-Jesse-Jiaze** [comment]
你可以自行diff一下这份代码和[ov_secondary](https://github.com/rpng/ov_secondary)

另外如果你想询问一些其他细节可以添加我的其他联系方式，尽量保持一个Issue下面只有一个问题

**Comment by WuZihao12** [comment]
h好滴谢谢
